version: '3.3'
services:
  app:
    image: 'ghcr.io/michivonah/moodle-docker'
    restart: on-failure:5
    ports:
      - '8080:80'
    environment:
      DB_DATABASE: "moodledb"
      DB_USER: "moodle"
      DB_PASSWORD: "moodle"
    volumes:
      - ./data:/var/www
    depends_on:
      - db

  db:
    image: 'mariadb:latest'
    restart: on-failure:5
    environment:
      MYSQL_ROOT_PASSWORD: "moodle"
      MYSQL_DATABASE: "moodledb"
      MYSQL_USER: "moodle"
      MYSQL_PASSWORD: "moodle"
    volumes:
      - ./db:/var/lib/mysql